version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          name: Analyze on SonarQube Cloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=SimoneRemoli_RouteX_Shortest_Path

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
